### ISSUE TITLE
Should DM people as to why they were kicked/banned

### ISSUE THREAD

**Issue by InfinityPlus05** [JuhJuhButts/BruhBot#1]
Obvious request

**Comment by joelnedev** [comment]
in progress, at troubleshooting stage

**Comment by joelnedev** [comment]
closed because there is no reason for BruhBot to have kick/ban commands anymore, UnbelievaBruh is now the moderation bot

**Comment by joelnedev** [comment]
Update on kicking/banning: this type of moderation will remain with UnbelievaBruh, but non-functioning kick and ban commands are being added to BruhBot _for the meme._
