### ISSUE TITLE
Should have a command to assign roles

### ISSUE THREAD

**Issue by InfinityPlus05** [JuhJuhButts/BruhBot#2]
But only for small roles, like say, Elliot Anderson or Can do pornhub live

**Comment by joelnedev** [comment]
adding to to-do list in README.md

**Comment by joelnedev** [comment]
Right, then what would be a major role?

**Comment by InfinityPlus05** [comment]
A major role is ones that can actually do something and aren’t just a cute lil color accessory

**Comment by joelnedev** [comment]
Ah. So what youre saying is allow users to assign themselves roles that

  *   Are cosmetic
  *   Grant access to a minor channel (e.g. hackermens or CS-updates)
  *   Do not grant access to major perms (e.g. manage channels)
This will mean that the only way to get roles such as Imaginationer is for me to grant it to you personally.

**Comment by InfinityPlus05** [comment]
Yes

**Comment by joelnedev** [comment]
can you suggest some syntax? What command(s) and arguments would a user use? Keep in mind that a space separates arguments. what this means is that if you intended a space(s) in one argument, it would be split into multiple arguments. That is why ```--kick``` requires underscores or dashes in the reason argument.

**Comment by InfinityPlus05** [comment]
Perhaps something like
--role add @rolenamehere
or
--r+ @rolenamehere
Using it would give the role to the person who used it
And
--role remove @rolenamehere
or
--r- @rolenamehere
To do the opposite effect
For mods, they could add a user after the initial command to give them the role. (Could be a shortcut to mute someone)

**Comment by joelnedev** [comment]
I understand your point, but ```r+``` would be a separate command from ```r-```. Will make pull request and link.

**Comment by joelnedev** [comment]
closed because UnbelievaBruh has this capability, and it has already been set up

**Comment by joelnedev** [comment]
Reopened because I need something else to do with BruhBot

**Comment by joelnedev** [comment]
Closed because this has been fulfilled with the latest commit
